### ISSUE TITLE
Need to rescue_from CanCan::AccessDenied

### ISSUE THREAD

**Issue by tylercollier** [rzane/grape-cancan#1]
Cool project!

Using `authorize!` raises a `CanCan::AccessDenied`, which is good. But it's not caught by default by grape-cancan. It would be great if grape-cancan could automatically put this on my API classes which extend `Grape::API`:

```
rescue_from CanCan::AccessDenied do
  error!('403 Forbidden', 403)
end
```

**Comment by tylercollier** [comment]
Well, the word "automatically" is the problem there. The best I can come up with is to ask the developer using this library to put `include Grape::CanCan::API` in their class that extends `Grape::API`.

Then, if grape-cancan's API module looks like the following, it works:

``` ruby
module API
  extend ActiveSupport::Concern

  included do
    rescue_from ::CanCan::AccessDenied do
      error!('403 Forbidden', 403)
    end
  end
  # Convienience method to authorize every route
  def authorize_routes!
    before { authorize_route! }
  end
end
```

**Comment by rzane** [comment]
This is definitely something that should be documented, but I don't think grape-cancan should handle exceptions automatically. When using cancancan with Rails, you'd have to manually add a `rescue_from` anyway. See https://github.com/CanCanCommunity/cancancan#3-handle-unauthorized-access.

Would you be willing to submit a PR documenting this?

**Comment by tylercollier** [comment]
I'd be happy to do a PR for documentation. I can't get to it right now but I have it on my calendar for July 19.

**Comment by rzane** [comment]
Okay, sounds good!
